# Generated by Django 3.2.19 on 2023-09-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_rename_username_register_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='register_tb',
        ),
    ]
